name: Deploy from main
# Controls when the workflow will run

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Confirm start'
        required: false
        default: 'yes'

  # 21:00 UTC daily (≈ 00:00 Arabia Standard Time GMT + 3).
  schedule:
    - cron: '0 21 * * *'

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOT_ENV: ${{ secrets.DOT_ENV }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Create .env file
        run: printf '%s' "${{ env.DOT_ENV }}" > .//.env

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/site:${GITHUB_REF#refs/heads/} ./
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/site:${GITHUB_REF#refs/heads/}
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://wazen.sa
    needs: Build
    env:
      DOT_ENV: ${{ secrets.DOT_ENV }}
    steps:
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_OCI }}
      - name: Deploy to main
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_HOST_OCI }} "\
            printf '%s' '${{ env.DOT_ENV }}' > .env && \
            sudo docker compose pull site && \
            sudo docker compose up -d && \
            sudo docker system prune -af"
